from typing import Any

class object:
    def __init__(self) -> None: ...
    def __new__(cls, *args: Any, **kwargs: Any) -> Any: ...

class type(object): ...
class int(object): ...
class float(object): ...
class bool(int): ...
class str(object): ...
class list(object): ...
class dict(object): ...
class tuple(object): ...
class set(object): ...
class frozenset(object): ...
class complex(object): ...
class bytes(object): ...
class bytearray(object): ...
class memoryview(object): ...
class range(object): ...
class slice(object): ...
class property(object): ...
class staticmethod(object): ...
class classmethod(object): ...

class BaseException(object): ...
class Exception(BaseException): ...
class ValueError(Exception): ...
class TypeError(Exception): ...
class AttributeError(Exception): ...
class NameError(Exception): ...
class KeyError(Exception): ...
class IndexError(Exception): ...
class ImportError(Exception): ...
class RuntimeError(Exception): ...
class NotImplementedError(RuntimeError): ...
class StopIteration(Exception): ...
class StopAsyncIteration(Exception): ...
class GeneratorExit(BaseException): ...
class SystemExit(BaseException): ...
class OSError(Exception): ...

def len(obj: Any) -> int: ...
def print(*values: Any, sep: Any = ..., end: Any = ..., file: Any = ..., flush: Any = ...) -> None: ...
def input(prompt: Any = ...) -> str: ...
def isinstance(obj: Any, class_or_tuple: Any) -> bool: ...
def issubclass(cls: Any, class_or_tuple: Any) -> bool: ...
def id(obj: Any) -> int: ...
def open(file: Any, mode: Any = ..., buffering: Any = ..., encoding: Any = ..., errors: Any = ..., newline: Any = ..., closefd: Any = ..., opener: Any = ...) -> Any: ...
def abs(x: Any) -> Any: ...
def min(*args: Any) -> Any: ...
def max(*args: Any) -> Any: ...
def sum(iterable: Any, start: Any = ...) -> Any: ...
def all(iterable: Any) -> bool: ...
def any(iterable: Any) -> bool: ...
def dir(obj: Any = ...) -> list[str]: ...
def repr(obj: Any) -> str: ...
def hasattr(obj: Any, name: str) -> bool: ...
def getattr(obj: Any, name: str, default: Any = ...) -> Any: ...
def setattr(obj: Any, name: str, value: Any) -> None: ...
def delattr(obj: Any, name: str) -> None: ...
def globals() -> dict[str, Any]: ...
def locals() -> dict[str, Any]: ...
def vars(obj: Any = ...) -> dict[str, Any]: ...
def callable(obj: Any) -> bool: ...
def iter(obj: Any, sentinel: Any = ...) -> Any: ...
def next(iterator: Any, default: Any = ...) -> Any: ...
def eval(expression: Any, globals: Any = ..., locals: Any = ...) -> Any: ...
def exec(object: Any, globals: Any = ..., locals: Any = ...) -> None: ...
def compile(source: Any, filename: Any, mode: Any, flags: Any = ..., dont_inherit: Any = ..., optimize: Any = ...) -> Any: ...
def format(value: Any, format_spec: Any = ...) -> str: ...
def hash(obj: Any) -> int: ...
def help(obj: Any = ...) -> None: ...
def ord(c: str) -> int: ...
def chr(i: int) -> str: ...
def bin(x: Any) -> str: ...
def oct(x: Any) -> str: ...
def hex(x: Any) -> str: ...
def sorted(iterable: Any, *, key: Any = ..., reverse: bool = ...) -> list[Any]: ...
def reversed(seq: Any) -> Any: ...
def enumerate(iterable: Any, start: int = ...) -> Any: ...
def zip(*iterables: Any) -> Any: ...
def map(func: Any, *iterables: Any) -> Any: ...
def filter(func: Any, iterable: Any) -> Any: ...
def pow(x: Any, y: Any, z: Any = ...) -> Any: ...
def round(number: Any, ndigits: Any = ...) -> Any: ...
def divmod(a: Any, b: Any) -> tuple[Any, Any]: ...
def exit(code: Any = ...) -> None: ...
def quit(code: Any = ...) -> None: ...
def breakpoint(*args: Any, **kwargs: Any) -> None: ...