import typing

class object:
    def __init__(self) -> None: ...
    def __new__(cls, *args: Any, **kwargs: Any) -> function: ...

class type: ...
class super: ...
class function: ...
class module: ...