from __future__ import annotations

from typing import (
	Any, 
	Generic,
	TypeVar,
	Unpack,
	TypeVarTuple
)

from collections.abc import (
    MutableSequence,
    MutableMapping,
    MutableSet,
    Sequence,
    Iterable,
    Set
)

from types import GenericAlias 

T = TypeVar('T')
K = TypeVar('K')
V = TypeVar('V')
Ts = TypeVarTuple('Ts')

class object:
	def __init__(self) -> None: ...
	def __new__(cls, *args: Any, **kwargs: Any) -> type: ...
	def __repr__(self) -> str: ...

class super: ...
class function: ...
class module: ...
class NoneType: ...
class ellipsis: ...
class _NotImplemented: ...

NotImplemented = _NotImplemented()
Ellipsis = ellipsis()

class type(Generic[T]):
    def __init__(self, obj: T) -> None: ...

    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class list(MutableSequence[T]):
    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class set(MutableSet[T]):
    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class dict(MutableMapping[K, V]):
    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class frozenset(Set[T]):
    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class tuple(Generic[Unpack[Ts]]):
    @classmethod
    def __class_getitem__(cls, item) -> GenericAlias: ...

class int:
    def __add__(self, other: int) -> int: ...
    def __sub__(self, other: int) -> int: ...
    def __mul__(self, other: int) -> int: ...
    def __truediv__(self, other: int) -> float: ...
    def __floordiv__(self, other: int) -> int: ...
    def __mod__(self, other: int) -> int: ...
    def __pow__(self, other: int, modulo: int | None = None) -> int: ...
    def __neg__(self) -> int: ...
    def __pos__(self) -> int: ...
    def __abs__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: int) -> bool: ...
    def __le__(self, other: int) -> bool: ...
    def __gt__(self, other: int) -> bool: ...
    def __ge__(self, other: int) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def bit_length(self) -> int: ...
    def to_bytes(self, length: int, byteorder: str, *, signed: bool = False) -> bytes: ...
    def from_bytes(bytes: bytes, byteorder: str, *, signed: bool = False) -> int: ...
class bool(int): ...
class float:
    def __add__(self, other: float) -> float: ...
    def __sub__(self, other: float) -> float: ...
    def __mul__(self, other: float) -> float: ...
    def __truediv__(self, other: float) -> float: ...
    def __floordiv__(self, other: float) -> float: ...
    def __mod__(self, other: float) -> float: ...
    def __pow__(self, other: float) -> float: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: float) -> bool: ...
    def __le__(self, other: float) -> bool: ...
    def __gt__(self, other: float) -> bool: ...
    def __ge__(self, other: float) -> bool: ...
    def __abs__(self) -> float: ...
    def __repr__(self) -> str: ...
    def is_integer(self) -> bool: ...
    def hex(self) -> str: ...
class str(Sequence[str]):
    def __add__(self, other: str) -> str: ...
    def __mul__(self, n: int) -> str: ...
    def __mod__(self, values: Any) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: str) -> bool: ...
    def __le__(self, other: str) -> bool: ...
    def __gt__(self, other: str) -> bool: ...
    def __ge__(self, other: str) -> bool: ...
    def __repr__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def format(self, *args: Any, **kwargs: Any) -> str: ...
    def join(self, iterable: Iterable[str]) -> str: ...
    def split(self, sep: str | None = None, maxsplit: int = -1) -> list[str]: ...
    def strip(self, chars: str | None = None) -> str: ...
    def replace(self, old: str, new: str, count: int = -1) -> str: ...
    def upper(self) -> str: ...
    def lower(self) -> str: ...
    def find(self, sub: str, start: int = 0, end: int = -1) -> int: ...
    def encode(self, encoding: str = 'utf-8', errors: str = 'strict') -> bytes: ...
    def startswith(self, prefix: Any, start: int = 0, end: int = -1) -> bool: ...
    def endswith(self, suffix: Any, start: int = 0, end: int = -1) -> bool: ...
class complex:
    def __add__(self, other: Any) -> complex: ...
    def __sub__(self, other: Any) -> complex: ...
    def __mul__(self, other: Any) -> complex: ...
    def __truediv__(self, other: Any) -> complex: ...
    def __abs__(self) -> float: ...
    def __eq__(self, other: Any) -> bool: ...
    def conjugate(self) -> complex: ...
    def real(self) -> float: ...
    def imag(self) -> float: ...
    def __repr__(self) -> str: ...

class bytes: ...
class bytearray: ...
class memoryview: ...
class range: ...
class slice: ...
class property: ...
class staticmethod: ...
class classmethod: ...

class BaseException: ...
class Exception: ...
class ValueError: ...
class TypeError: ...
class AttributeError: ...
class NameError: ...
class KeyError: ...
class IndexError: ...
class ImportError: ...
class RuntimeError: ...
class NotImplementedError: ...
class StopIteration: ...
class StopAsyncIteration: ...
class GeneratorExit: ...
class SystemExit: ...
class OSError: ...

def len(obj: Any) -> int: ...
def print(*values: Any, sep: Any = ..., end: Any = ..., file: Any = ..., flush: Any = ...) -> None: ...
def input(prompt: Any = ...) -> str: ...
def isinstance(obj: Any, class_or_tuple: Any) -> bool: ...
def issubclass(cls: Any, class_or_tuple: Any) -> bool: ...
def id(obj: Any) -> int: ...
def open(file: Any, mode: Any = ..., buffering: Any = ..., encoding: Any = ..., errors: Any = ..., newline: Any = ..., closefd: Any = ..., opener: Any = ...) -> Any: ...
def abs(x: Any) -> Any: ...
def min(*args: Any) -> Any: ...
def max(*args: Any) -> Any: ...
def sum(iterable: Any, start: Any = ...) -> Any: ...
def all(iterable: Any) -> bool: ...
def any(iterable: Any) -> bool: ...
def dir(obj: Any = ...) -> list[str]: ...
def repr(obj: Any) -> str: return obj.__repr__()
def hasattr(obj: Any, name: str) -> bool: ...
def getattr(obj: Any, name: str, default: Any = ...) -> Any: ...
def setattr(obj: Any, name: str, value: Any) -> None: ...
def delattr(obj: Any, name: str) -> None: ...
def globals() -> dict[str, Any]: ...
def locals() -> dict[str, Any]: ...
def vars(obj: Any = ...) -> dict[str, Any]: ...
def callable(obj: Any) -> bool: ...
def iter(obj: Any, sentinel: Any = ...) -> Any: ...
def next(iterator: Any, default: Any = ...) -> Any: ...
def eval(expression: Any, globals: Any = ..., locals: Any = ...) -> Any: ...
def exec(object: Any, globals: Any = ..., locals: Any = ...) -> None: ...
def compile(source: Any, filename: Any, mode: Any, flags: Any = ..., dont_inherit: Any = ..., optimize: Any = ...) -> Any: ...
def format(value: Any, format_spec: Any = ...) -> str: ...
def hash(obj: Any) -> int: ...
def help(obj: Any = ...) -> None: ...
def ord(c: str) -> int: ...
def chr(i: int) -> str: ...
def bin(x: Any) -> str: ...
def oct(x: Any) -> str: ...
def hex(x: Any) -> str: ...
def sorted(iterable: Any, *, key: Any = ..., reverse: bool = ...) -> list[Any]: ...
def reversed(seq: Any) -> Any: ...
def enumerate(iterable: Any, start: int = ...) -> Any: ...
def zip(*iterables: Any) -> Any: ...
def map(func: Any, *iterables: Any) -> Any: ...
def filter(func: Any, iterable: Any) -> Any: ...
def pow(x: Any, y: Any, z: Any = ...) -> Any: ...
def round(number: Any, ndigits: Any = ...) -> Any: ...
def divmod(a: Any, b: Any) -> tuple[Any, Any]: ...
def exit(code: Any = ...) -> None: ...
def quit(code: Any = ...) -> None: ...
def breakpoint(*args: Any, **kwargs: Any) -> None: ...