from typing import (
    Any, 
    Generic,
    TypeVar,
    Unpack,
    TypeVarTuple
)

T = TypeVar('T')
K = TypeVar('K')
V = TypeVar('V')
Ts = TypeVarTuple('Ts')

class object:
    def __init__(self) -> None: ...
    def __new__(cls, *args: Any, **kwargs: Any) -> Any: ...

class super: ...
class function: ...
class module: ...
class NoneType: ...
class int: ...
class float: ...
class bool: ...
class str: ...
class type(Generic[T]): ...
class list(Generic[T]): ...
class dict(Generic[K, V]): ...
class set(Generic[T]): ...
class frozenset(Generic[T]): ...
class tuple(Generic[Unpack[Ts]]): ...
class complex: ...
class bytes: ...
class bytearray: ...
class memoryview: ...
class range: ...
class slice: ...
class property: ...
class staticmethod: ...
class classmethod: ...

class BaseException: ...
class Exception: ...
class ValueError: ...
class TypeError: ...
class AttributeError: ...
class NameError: ...
class KeyError: ...
class IndexError: ...
class ImportError: ...
class RuntimeError: ...
class NotImplementedError: ...
class StopIteration: ...
class StopAsyncIteration: ...
class GeneratorExit: ...
class SystemExit: ...
class OSError: ...

def len(obj: Any) -> int: ...
def print(*values: Any, sep: Any = ..., end: Any = ..., file: Any = ..., flush: Any = ...) -> None: ...
def input(prompt: Any = ...) -> str: ...
def isinstance(obj: Any, class_or_tuple: Any) -> bool: ...
def issubclass(cls: Any, class_or_tuple: Any) -> bool: ...
def id(obj: Any) -> int: ...
def open(file: Any, mode: Any = ..., buffering: Any = ..., encoding: Any = ..., errors: Any = ..., newline: Any = ..., closefd: Any = ..., opener: Any = ...) -> Any: ...
def abs(x: Any) -> Any: ...
def min(*args: Any) -> Any: ...
def max(*args: Any) -> Any: ...
def sum(iterable: Any, start: Any = ...) -> Any: ...
def all(iterable: Any) -> bool: ...
def any(iterable: Any) -> bool: ...
def dir(obj: Any = ...) -> list[str]: ...
def repr(obj: Any) -> str: ...
def hasattr(obj: Any, name: str) -> bool: ...
def getattr(obj: Any, name: str, default: Any = ...) -> Any: ...
def setattr(obj: Any, name: str, value: Any) -> None: ...
def delattr(obj: Any, name: str) -> None: ...
def globals() -> dict[str, Any]: ...
def locals() -> dict[str, Any]: ...
def vars(obj: Any = ...) -> dict[str, Any]: ...
def callable(obj: Any) -> bool: ...
def iter(obj: Any, sentinel: Any = ...) -> Any: ...
def next(iterator: Any, default: Any = ...) -> Any: ...
def eval(expression: Any, globals: Any = ..., locals: Any = ...) -> Any: ...
def exec(object: Any, globals: Any = ..., locals: Any = ...) -> None: ...
def compile(source: Any, filename: Any, mode: Any, flags: Any = ..., dont_inherit: Any = ..., optimize: Any = ...) -> Any: ...
def format(value: Any, format_spec: Any = ...) -> str: ...
def hash(obj: Any) -> int: ...
def help(obj: Any = ...) -> None: ...
def ord(c: str) -> int: ...
def chr(i: int) -> str: ...
def bin(x: Any) -> str: ...
def oct(x: Any) -> str: ...
def hex(x: Any) -> str: ...
def sorted(iterable: Any, *, key: Any = ..., reverse: bool = ...) -> list[Any]: ...
def reversed(seq: Any) -> Any: ...
def enumerate(iterable: Any, start: int = ...) -> Any: ...
def zip(*iterables: Any) -> Any: ...
def map(func: Any, *iterables: Any) -> Any: ...
def filter(func: Any, iterable: Any) -> Any: ...
def pow(x: Any, y: Any, z: Any = ...) -> Any: ...
def round(number: Any, ndigits: Any = ...) -> Any: ...
def divmod(a: Any, b: Any) -> tuple[Any, Any]: ...
def exit(code: Any = ...) -> None: ...
def quit(code: Any = ...) -> None: ...
def breakpoint(*args: Any, **kwargs: Any) -> None: ...