import typing as _typing
import types as _types 

_T = _typing.TypeVar('_T')
_K = _typing.TypeVar('_K')
_V = _typing.TypeVar('_V')
_Ts = _typing.TypeVarTuple('_Ts')

class object:
	def __init__(self) -> None: ...
	def __new__(cls, *args, **kwargs) -> type: ...
	def __repr__(self) -> str: ...

class NoneType: ...
class ellipsis: ...
class _NotImplemented: ...

NotImplemented = _NotImplemented()
Ellipsis = ellipsis()

class super: ...
class function: ...
class module: ...
class int: ...
class float: ...
class bool: ...
class str: ...

class type(_typing.Generic[_T]):
	def __init__(self, obj: _T) -> None: ...
	def __or__(self, other: type) -> _types.UnionType: ...

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...

class list(_typing.Generic[_T]): 

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class set(_typing.Generic[_T]):

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class dict(_typing.Generic[_K, _V]):

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class frozenset(_typing.Generic[_T]): 

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class tuple(_typing.Generic[_typing.Unpack[_Ts]]): 

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class complex: ...
class bytes: ...
class bytearray: ...
class memoryview: ...
class range: ...
class slice: ...
class property: ...
class staticmethod: ...
class classmethod: ...

class BaseException: ...
class Exception: ...
class ValueError: ...
class TypeError: ...
class AttributeError: ...
class NameError: ...
class KeyError: ...
class IndexError: ...
class ImportError: ...
class RuntimeError: ...
class NotImplementedError: ...
class StopIteration: ...
class StopAsyncIteration: ...
class GeneratorExit: ...
class SystemExit: ...
class OSError: ...

def len(obj) -> int: ...
def print(*values, sep = ..., end = ..., file = ..., flush = ...) -> None: ...
def input(prompt = ...) -> str: ...
def isinstance(obj, class_or_tuple) -> bool: ...
def issubclass(cls, class_or_tuple) -> bool: ...
def id(obj) -> int: ...
def open(file, mode = ..., buffering = ..., encoding = ..., errors = ..., newline = ..., closefd = ..., opener = ...) -> _types.Any: ...
def abs(x) -> _types.Any: ...
def min(*args) -> _types.Any: ...
def max(*args) -> _types.Any: ...
def sum(iterable, start = ...) -> _types.Any: ...
def all(iterable) -> bool: ...
def any(iterable) -> bool: ...
def dir(obj = ...) -> list[str]: ...
def repr(obj) -> str: return obj.__repr__()
def hasattr(obj, name: str) -> bool: ...
def getattr(obj, name: str, default = ...) -> _types.Any: ...
def setattr(obj, name: str, value) -> None: ...
def delattr(obj, name: str) -> None: ...
def globals() -> dict[str, _types.Any]: ...
def locals() -> dict[str, _types.Any]: ...
def vars(obj = ...) -> dict[str, _types.Any]: ...
def callable(obj) -> bool: ...
def iter(obj, sentinel = ...) -> _types.Any: ...
def next(iterator, default = ...) -> _types.Any: ...
def eval(expression, globals = ..., locals = ...) -> _types.Any: ...
def exec(object, globals = ..., locals = ...) -> None: ...
def compile(source, filename, mode, flags = ..., dont_inherit = ..., optimize = ...) -> _types.Any: ...
def format(value, format_spec = ...) -> str: ...
def hash(obj) -> int: ...
def help(obj = ...) -> None: ...
def ord(c: str) -> int: ...
def chr(i: int) -> str: ...
def bin(x) -> str: ...
def oct(x) -> str: ...
def hex(x) -> str: ...
def sorted(iterable, *, key = ..., reverse: bool = ...) -> list[_types.Any]: ...
def reversed(seq) -> _types.Any: ...
def enumerate(iterable, start: int = ...) -> _types.Any: ...
def zip(*iterables) -> _types.Any: ...
def map(func, *iterables) -> _types.Any: ...
def filter(func, iterable) -> _types.Any: ...
def pow(x, y, z = ...) -> _types.Any: ...
def round(number, ndigits = ...) -> _types.Any: ...
def divmod(a, b) -> tuple[_types.Any, _types.Any]: ...
def exit(code = ...) -> None: ...
def quit(code = ...) -> None: ...
def breakpoint(*args, **kwargs) -> None: ...