class Generic: ...
class TypeVar: ...
class TypeVarTuple: ...
class Unpack: ...
class Any: ...
class _GenericAlias: ...

T = TypeVar('T')
K = TypeVar('K')
V = TypeVar('V')
Ts = TypeVarTuple('Ts')

class Optional(Generic[T]): ...
class Union(Generic[Unpack[Ts]]): ...
class Literal(Generic[Unpack[Ts]]): ...
class Annotated(Generic[T, Unpack[Ts]]): ...
class Final(Generic[T]): ...
class ClassVar(Generic[T]): ...
class NoReturn: ...
class NewType: ...

class List(Generic[T]): ...
class Set(Generic[T]): ...
class Dict(Generic[K, V]): ...
class Tuple(Generic[Unpack[Ts]]): ...
class FrozenSet(Generic[T]): ...
class DefaultDict(Generic[K, V]): ...
class Counter(Generic[T]): ...
class ChainMap(Generic[K, V]): ...
class Deque(Generic[T]): ...

class Type(Generic[T]): ...
class Callable(Generic[Unpack[Ts], T]): ...
class Generator(Generic[T, V, K]): ...
class AsyncGenerator(Generic[T, V]): ...
class Coroutine(Generic[T, V, K]): ...
class Awaitable(Generic[T]): ...
class AsyncIterable(Generic[T]): ...
class AsyncIterator(AsyncIterable[T], Generic[T]): ...