class Generic: ...
class TypeVar:
    def __init__(self, name: str):...
class TypeVarTuple:
    def __init__(self, name: str):...
class Unpack: ...
class Optional: ...
class NewType: ...
class Literal: ...
class List: ...
class Set: ...
class Dict: ...
class Tuple: ...
class Union: ...
class Callable: ...
class Type: ...
class Any: ...

class _GenericAlias: ...