from collections.abc import (
    MutableSequence,
    MutableMapping,
    MutableSet
)

class Any: ...
class TypeVar: ...
class TypeVarTuple: ...
class NoReturn: ...
class NewType: ...

T = TypeVar('T')
K = TypeVar('K')
V = TypeVar('V')
Ts = TypeVarTuple('Ts')

class _GenericAlias: ...
class _UnpackGenericAlias: ...
class _UnionGenericAlias: ...
class _LiteralGenericAlias: ...
	
class Unpack: 
    @classmethod
    def __class_getitem__(cls, item) -> _UnpackGenericAlias: ...

class Generic: 
    @classmethod
    def __class_getitem__(cls, item) -> _GenericAlias: ...

class Literal(Generic[Unpack[Ts]]): 
    @classmethod
    def __class_getitem__(cls, item) -> _LiteralGenericAlias: ...

class Union(Generic[Unpack[Ts]]):
    @classmethod
    def __class_getitem__(cls, item) -> _UnionGenericAlias: ...

class Optional(Generic[T]): 
    @classmethod
    def __class_getitem__(cls, item) -> _UnionGenericAlias: ...

class Annotated(Generic[T, Unpack[Ts]]): ...
class Final(Generic[T]): ...
class ClassVar(Generic[T]): ...

class List(MutableSequence[T]): ...
class Deque(MutableSequence[T]): ...

class Dict(MutableMapping[K, V]): ...
class DefaultDict(Dict[K, V]): ...
class Counter(Dict[T, int]): ...
class ChainMap(MutableMapping[K, V]): ...

class Set(MutableSet[T]): ...
class FrozenSet(Set[T]): ...

class Tuple(Generic[Unpack[Ts]]): ...
class Type(Generic[T]): ...
class Generator(Generic[T, V, K]): ...
class AsyncGenerator(Generic[T, V]): ...
class Coroutine(Generic[T, V, K]): ...
class Awaitable(Generic[T]): ...
class AsyncIterable(Generic[T]): ...
class AsyncIterator(AsyncIterable[T]): ...