from __future__ import annotations
from typing import (
    TypeVar, 
    Generic
)

T = TypeVar('T')
K = TypeVar('K')
V = TypeVar('V')

class Iterable(Generic[T]):
    def __iter__(self) -> Iterator[T]: ...

class Container(Generic[T]):
    def __contains__(self, item: object) -> bool: ...

class Iterator(Iterable[T]):
    def __next__(self) -> T: ...

class Sized:
    def __len__(self) -> int: ...

class Sequence(Sized, Iterable[T], Container[T]):
    def __getitem__(self, index: int) -> T: ...

class MutableSequence(Sequence[T]):
    def __setitem__(self, index: int, value: T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def insert(self, index: int, value: T) -> None: ...
    def append(self, value: T) -> None: ...
    def pop(self, index: int = ...) -> T: ...

class Mapping(Sized, Iterable[K], Container[K], Generic[K, V]):
    def __getitem__(self, key: K) -> V: ...

class MutableMapping(Mapping[K, V]):
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...

class Collection(Sized, Iterable[T], Container[T]):...

class Set(Collection[T]):
    def __T__(self) -> T:...
    def __le__(self, other: Set) -> bool: ...
    def __lt__(self, other: Set) -> bool: ...
    def __ge__(self, other: Set) -> bool: ...
    def __gt__(self, other: Set) -> bool: ...
    def __or__(self, other: Set) -> Set: return {self.__T__(), other.__T__()}
    def __and__(self, other: Set) -> Set: return {self.__T__(), other.__T__()}
    def __sub__(self, other: Set) -> Set: return {self.__T__(), other.__T__()}
    def __xor__(self, other: Set) -> Set: return {self.__T__(), other.__T__()}
    def isdisjoint(self, other: Set) -> bool: ...

class MutableSet(Set[T]):
    def add(self, value: T) -> None: ...
    def discard(self, value: T) -> None: ...
    def remove(self, value: T) -> None: ...
    def pop(self) -> T: ...
    def clear(self) -> None: ...
    def update(self, *others: Iterable[T]) -> None: ...
    def intersection_update(self, *others: Iterable[T]) -> None: ...
    def difference_update(self, *others: Iterable[T]) -> None: ...
    def symmetric_difference_update(self, other: Iterable[T]) -> None: ...
